server.port=9091
spring.application.name=ms-ofertas

# Config de la Base de Datos db_ofertas
spring.datasource.url=jdbc:mysql://localhost:3306/db_ofertas?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Dejamos que el Liquibase mande
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true