server.port=8085
spring.datasource.url=jdbc:mysql://localhost:3306/db_componentes?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# hibernate apagao pa que la wea del liquibase haga la pega
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# liquibase activado
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml